# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - main

pool:
  name: 'Devopsadvanceagent'

variables:
  acrName: 'acrprod9838'
  acrLoginServer: 'acrprod9838.azurecr.io'
  imageName: 'july-calendar'
  imageTag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'   # ⚠️ apna actual Dockerfile path daalo
  buildContext: '$(Build.SourcesDirectory)'                 # ⚠️ Dockerfile jis folder mein hai
  containerName: 'july-calendar-app'
  hostPort: '8080'      # browser mein yeh port khologe
  containerPort: '80'   # ⚠️ apni app ka actual port daalo (Dockerfile ke EXPOSE se check karo)

steps:
- checkout: self
  displayName: 'Checkout Source Code'

- task: PowerShell@2
  displayName: 'Check Docker & Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Docker Version:"
      docker --version
      Write-Host "Azure CLI Version:"
      az --version