# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - main

pool:
  name: 'Devopsadvanceagent'

variables:
  acrName: 'acrprod9838'
  acrLoginServer: 'acrprod9838.azurecr.io'
  imageName: 'july-calendar'
  imageTag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'   # ⚠️ apna actual path daalo agar root mein nahi hai
  buildContext: '$(Build.SourcesDirectory)'                 # ⚠️ Dockerfile jis folder mein hai

steps:
- checkout: self
  displayName: 'Checkout Source Code'

- task: PowerShell@2
  displayName: 'Check Docker & Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "===== Docker Version